%% Documentation of the workspace 'NGA_W1_meta_data.mat'
%
% This workspace has been created based on the PEER NGA database ground
% motions (Chiou et al. 2008). The documentation of the variables provided
% here is based on the NGA Documentation file available at:
% http://peer.berkeley.edu/nga/documentation.html
%
% Not all the variables available in the workspace may be required for the
% ground-motion selection. The minimum requirements have been documented in
% Select_Ground_Motions.m
%
% Nirmal Jayaram, Ting Lin, Jack W. Baker
% Department of Civil and Environmental Engineering
% Stanford University
% Last Updated: 27 March 2010
%
% Referenced manuscripts:
%
% Chiou, B., R. Darragh, N. Gregor, and W. Silva (2008). NGA project 
% strong-motion database. Earthquake Spectra 24(1), 23–44.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%% Downloading simulated time histories for selected ground motions
% An account will be needed with the Southern California Earthquake Center
% in order to access the results from various ground motion simulations.
% The links provided in the Output file generated by the
% Select_Ground_Motions script lead to a list of simulation numbers, while
% the filenames displayed in the Output file indicate the folder number and
% station (i.e. which links) to choose to access the appropriate time
% history. For each filename, the folder number will begin at 10000000 and
% the station number will appear after (e.g. for simulation 10000003.9001,
% 10000003 is the folder number and 9001 is the station number). Each of
% the time histories is located in a .acc file.

%% 

% Filename_1        : Filename of the time history data file in direction 1
% Filename_2        : Filename of the time history data file in direction 2
% dirLocation       : Link to the appropriate SCEC ground motion simulation
%                     results page
% Periods           : Periods at which spectral accelerations have been
%                     computed and stored in the workspace
% Sa_1              : Spectral acceleration in direction 1
% Sa_2              : Spectral acceleration in direction 2
% Sa_RotD100        : Orientation independent two-component spectral
%                     acceleration
% Sa_RotD50         : Orientation independent two-component spectral
%                     acceleration
% clostest_D        : Closest distance to the ruptured area
% magnitude         : Magnitude
% soil_Vs30         : Vs30 value














