%% Documentation of the workspace 'NGAW2_meta_data.mat'
%
% This workspace has been created based on the PEER NGA West 2 database ground
% motions The documentation of the variables provided
% here is based on the NGA Documentation file available at:
% http://peer.berkeley.edu/ngawest2/databases/
%
% Not all the variables available in the workspace may be required for the
% ground-motion selection. The minimum requirements have been documented in
% Select_Ground_Motions.m
%
% Nirmal Jayaram, Ting Lin, Jack W. Baker
% Department of Civil and Environmental Engineering
% Stanford University
% Last Updated: March 20, 2014 to use the NGA West 2 database
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Downloading time histories for selected ground motions 
% The instructions for downloading time series from the NGA-W2 database are
% summarized in the Output File. In order to retrieve the time histories
% for the ground motions ultimately selected, proceed to the link:
% ngawest2.berkeley.edu An account is needed to access the database. If you
% do not have an account, click "Sign-up" at the top of the page.
% 
% Once signed in, click the "NGA West2 enter" link on the right of the
% page. On the resulting page, select "No Scaling" under "Select Spectrum
% Model" and click submit. Under "Record Characteristics" enter the RSN
% (record sequence number) provided by the Output file generated by the
% Select_Ground_Motions script. The RSN values must be separated by commas.
% Click "Search Records."
%
% On the resulting page, scroll down to "Download Options" located near the
% bottom of the page and click "Download Time Series Records." For any
% message boxes that appear, click "OK." Save the resulting files. Each
% file provides the number of points (NPTS) and time step (DT) of the time
% history.

%% 

% Filename_1        : Filename of the time history data file in direction 1
% Filename_2        : Filename of the time history data file in direction 2
% Filename_vert     : Filename of the vertical time history data file
% dirLocation       : Link to the NGA-W2 page
% Periods           : Periods at which spectral accelerations have been
%                     computed and stored in the workspace
% Sa_1              : Spectral acceleration in direction 1
% Sa_2              : Spectral acceleration in direction 2
% Sa_vert           : Spectral acceleration in vertical direction
% Sa_RotD100        : Orientation independent two-component spectral
%                     acceleration
% Sa_RotD50         : Orientation independent two-component spectral
%                     acceleration
% distance_cambell  : Campbell distance
% closest_D         : Closest distance to the ruptured area
% distance_epi      : Epicentral distance
% distance_hyp      : Hypocentral distance
% distance_jb       : Joyner-Boore distance
% lowest_usable_freq: Lowest usable frequency
% magnitude         : Magnitude
% Mechanism         : Fault mechanism
% soil_Vs30         : Vs30 value














